### ISSUE TITLE
Deep-seq2seq-LSTM. batchsize

### ISSUE THREAD

**Issue by kikyou123** [samaonline/Hierarchical-Model-for-Long-term-Video-Prediction#1]
i think your Deep-seq2seq train datesets have only one? is it wrong?

**Comment by samaonline** [comment]
Sorry but I don't quite understand the question.

**Comment by kikyou123** [comment]
![image](https://user-images.githubusercontent.com/19486038/29756856-f0109b24-8bd9-11e7-87b8-b91e14726186.png)
i think it is : frames_train = top_frames[:150]

**Comment by samaonline** [comment]
Thanks for pointing out! I have fixed it.
