### ISSUE TITLE
can not find models/alexnet.npy', 'models/vgg16.npy', 

### ISSUE THREAD

**Issue by kikyou123** [samaonline/Hierarchical-Model-for-Long-term-Video-Prediction#2]
![image](https://user-images.githubusercontent.com/19486038/29614526-0729281c-883d-11e7-9e46-638ff00624ba.png)
i cant not see the models/alexnet.npy', 'models/vgg16.npy', where i can find them?

**Comment by samaonline** [comment]
Thanks for reporting the issues! I have fixed it and please take a look at README.md
