### ISSUE TITLE
analogy network imread

### ISSUE THREAD

**Issue by kikyou123** [samaonline/Hierarchical-Model-for-Long-term-Video-Prediction#3]
![image](https://user-images.githubusercontent.com/19486038/29755920-a42efb0e-8bd1-11e7-8f11-93f5edce0232.png)
the network input is [224,224,3],should the imread images imresize [224,224,3]？
and the network input should scale [0,1], or just [0, 255]?

**Comment by samaonline** [comment]
Thanks for asking.
Yes, you should resize the image size so that it matches the input size.
For scaling, we use [0, 255].
